config/routes.rb
Rails.application.routes.draw do
  resources :firms
  devise_for :users

  root 'firms#index'

end

app/models/firm.rb
class Firm < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :firms

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :time_zone, inclusion: { in: ActiveSupport::TimeZone.zones_map(&:name).keys } 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  around_filter :user_time_zone, if: :current_user
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :time_zone
  end

private

  def user_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
  end

  # GET /firms/new
  def new
    @firm = Firm.new
  end

  # GET /firms/1/edit
  def edit
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(firm_params)

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: 'Firm was successfully created.' }
        format.json { render :show, status: :created, location: @firm }
      else
        format.html { render :new }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firms/1
  # PATCH/PUT /firms/1.json
  def update
    respond_to do |format|
      if @firm.update(firm_params)
        format.html { redirect_to @firm, notice: 'Firm was successfully updated.' }
        format.json { render :show, status: :ok, location: @firm }
      else
        format.html { render :edit }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm.destroy
    respond_to do |format|
      format.html { redirect_to firms_url, notice: 'Firm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firm
      @firm = Firm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firm_params
      params.require(:firm).permit(:name, :tel, :time_zone, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def whattime (t)
  	Time.zone = t
  	Time.zone.now
  end
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/views/firms/_form.html.erb
<%= form_for(@firm) do |f| %>
  <% if @firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

      <ul>
      <% @firm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select( :time_zone, ActiveSupport::TimeZone.all, default: "Samara" ) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/firms/edit.html.erb
<h1>Editing Firm</h1>

<%= render 'form' %>

<%= link_to 'Show', @firm %> |
<%= link_to 'Back', firms_path %>

app/views/firms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Firms</h1>

<%= Time.zone.now %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tel</th>
      <th>Time zone</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firms.each do |firm| %>
      <tr>
        <td><%= firm.name %></td>
        <td><%= firm.tel %></td>
        <td><%= whattime firm.time_zone %></td>
        <td><%= firm.user_id %></td>
        <td><%= link_to 'Show', firm %></td>
        <td><%= link_to 'Edit', edit_firm_path(firm) %></td>
        <td><%= link_to 'Destroy', firm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firm', new_firm_path %>

app/views/firms/new.html.erb
<h1>New Firm</h1>

<%= render 'form' %>

<%= link_to 'Back', firms_path %>

app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>
<%= Time.zone.now %>
<p>
  <strong>Name:</strong>
  <%= @firm.name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @firm.tel %>
</p>

<p>
  <strong>Time zone:</strong>
  <%= whattime @firm.time_zone %>
</p>

<p>
  <strong>User:</strong>
  <%= @firm.user_id %>
</p>

<%= link_to 'Edit', edit_firm_path(@firm) %> |
<%= link_to 'Back', firms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tztime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>


<%= yield %>

</body>
</html>